package com.example.administrator.yangjinyang20170504.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CAR".
 */
public class car {

    private Long id;
    private String name;
    private String price;
    private String content;

    public car() {
    }

    public car(Long id) {
        this.id = id;
    }

    public car(Long id, String name, String price, String content) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
