package com.example.administrator.yangjinyang20170504.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.administrator.yangjinyang20170504.db.car;

import com.example.administrator.yangjinyang20170504.db.carDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carDaoConfig;

    private final carDao carDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carDaoConfig = daoConfigMap.get(carDao.class).clone();
        carDaoConfig.initIdentityScope(type);

        carDao = new carDao(carDaoConfig, this);

        registerDao(car.class, carDao);
    }
    
    public void clear() {
        carDaoConfig.getIdentityScope().clear();
    }

    public carDao getCarDao() {
        return carDao;
    }

}
